### ISSUE TITLE
Use a Keycard hardware wallet with Status

### ISSUE THREAD

**Issue by jorge-campo** [status-im/help.status.im#108]
This content describes the different interactions of Status desktop and mobile users who use a Keycard. Keycard workflows can be found on this [Figma file](https://www.figma.com/file/idUoxN7OIW2Jpp3PMJ1Rl8/%E2%9A%99%EF%B8%8F-Settings-%7C-Desktop?node-id=199%3A2653).

## ToC draft

  - Generate keys for a new Keycard (H2)
  - Login to your Status account with your Keycard (H2)
  - Sign Wallet transactions using Keycard (H2)
  - Troubleshooting (H2)
      - The Keycard is locked with existing keys
      - The Keycard is locked after unsuccessfully trying a PIN
      - The Keycard stores keys but doesn't store a profile
      - This Keycard is empty
      - The Keycard has been initialized
          - These three are related because the only way out is to generate new keys
      - Recover your Keycard

**Comment by cheny0** [comment]
Closing this issue because the content has been covered in https://github.com/status-im/status-website/issues/1150
