### ISSUE TITLE
Use DApps with the Status Browser

### ISSUE THREAD

**Issue by jorge-campo** [status-im/help.status.im#122]
Describe how to connect to decentralized apps or DApps using the Status Web3 Browser.

Use the content in the [Status FAQs](https://status.im/docs/FAQs.html) as the starting point:

- What is DAp.ps
- How do I vote for DApps
- What are DApp permissions

**Comment by jorge-campo** [comment]
Not a priority now. Most probably available in 2023 Q3.

**Comment by Fabiomorais87** [comment]
This is not available, so I am closing the issue.

**Comment by jorge-campo** [comment]
Superseded by https://github.com/status-im/status-website/issues/1182
