### ISSUE TITLE
Update Material for MkDocs to 'insiders' build

### ISSUE THREAD

**Issue by jorge-campo** [status-im/help.status.im#147]
Notes to myself:

- [ ] Set `mkdocs.yml` configuration inheritance
- [ ] Test configuration
- [ ] Update `mkdocs.yml` extensions
- [ ] Test configuration

**Comment by jorge-campo** [comment]
Hey @jakubgs, I'm assigning to you this issue, [as discussed](https://discord.com/channels/624205794384281629/626045898878877696/991993382819868672).

I will provide the token information separately.

**Goal:**
Update the CI so we can use the Material for Mkdocs 'insiders' build in the dev-help.status.im and help.status.im sites.

**Summary:**
To use the advanced functionality of Material for MkDocs 'insiders,' we need to change the python package we use in the CI.

Currently, Jenkins uses this command to install Material and build the site:

`pip install mkdocs-material==8.3.8`

To use the mkdocs-material-insiders build, pip install requires the GitHub token:

`pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git`

**Decision:**
Use Jenkins credentials.

**Comment by jakubgs** [comment]
Not sure if installing basic build dependencies from a private repos is a good idea, but there you go:

* https://github.com/status-im/help.status.im/pull/155

**Comment by jorge-campo** [comment]
> Not sure if installing basic build dependencies from a private repos is a good idea, but there you go:

Another option we have is to fork the private repo in the Status organization. If you think this is a better solution, we can also do that. Just let me know.

**Comment by jakubgs** [comment]
>Another option we have is to fork the private repo in the Status organization.

Changes nothing, it would still have to be private the the need for a token or SSH key would remain.

**Comment by jorge-campo** [comment]
> Changes nothing, it would still have to be private the the need for a token or SSH key would remain.

Well, we're just following the [Insider's installation how-to](https://squidfunk.github.io/mkdocs-material/insiders/getting-started/#installation) used by hundreds of other insiders, so I believe we're on the safe side 😉

**Comment by jorge-campo** [comment]
Hey @exebeeche,

From now on, we have two different configuration files in Material for MkDocs:

1. `/overrides/mkdocs.insiders.yml`, with contains the insiders' plugins only.
2. `/config/[language]/mkdocs.yml` with the configuration for each language.

We still build the site by using `mkdocs.yml`. This configuration file calls the insiders' `mkdocs.yml` file using [configuration inheritance](https://www.mkdocs.org/user-guide/configuration/#configuration-inheritance):

```
# Plugins
INHERIT: '../../overrides/mkdocs.insiders.yml'
```

Please, have a look at this PR and familiarize yourself with the new configuration structure. I have updated our [Notion page](https://www.notion.so/Configure-GitHub-repo-files-and-folders-8f1324b0f23f483289016a90227649a9) as well.

After merging this PR in your repo, you need to run these installs on your laptop to make insiders work:

1. Install the following packages via `brew`:

    `brew install cairo freetype libffi libjpeg libpng zlib`

3. Install these additional python packages:

    ```
    pip install mkdocs-git-authors-plugin
    pip install mkdocs-git-committers-plugin-2
    ```

**Comment by jakubgs** [comment]
No, packages should be installed using the [requirements.txt](https://github.com/status-im/help.status.im/blob/develop/requirements.txt) file,, because that's what it is for:
```sh
pip install --user -r requirements.txt
```

**Comment by jakubgs** [comment]
And if the packages you listed are necessary for builds, we should document this in `README.md` or someplace else, like `package.json` as a target.

**Comment by jorge-campo** [comment]
> No, packages should be installed using the [requirements.txt](https://github.com/status-im/help.status.im/blob/develop/requirements.txt) file, because that's what it is for:

My message refers to the local build on our computers, @jakubgs. We don't use `requirements.txt` for local builds (see [Building your site](https://squidfunk.github.io/mkdocs-material/creating-your-site/#building-your-site) for more information.)

Anyhow, the packages I mentioned are already in the `requirements.txt` file.

**Comment by jorge-campo** [comment]
> And if the packages you listed are necessary for builds, we should document this in `README.md` or someplace else, like `package.json` as a target.

I've just created https://github.com/status-im/help.status.im/issues/164 to track this down. Thanks.

**Comment by jakubgs** [comment]
>We don't use `requirements.txt` for local builds

Why not?
