### ISSUE TITLE
Dark and light themes - how to use custom icons and images

### ISSUE THREAD

**Issue by exebeeche** [status-im/help.status.im#153]

**Comment by jorge-campo** [comment]
See discussion in Material for MkDocs forum: https://github.com/squidfunk/mkdocs-material/discussions/4229

**Comment by jorge-campo** [comment]
We need to clarify first the icon set to use for the different platforms.

**Comment by jorge-campo** [comment]
I managed to make it work with the attached `test.svg` icon:

- I used the free and online SVG editor at [https://editsvgcode.com/#](https://editsvgcode.com/#)
- Removed the `fill` parameters (there is one per line on the icon graph)

We need to find now how to automate this process for the icon set.





![Image](https://user-images.githubusercontent.com/62282406/185220506-91d72371-13e6-4553-ac43-fe4719c80325.svg)
