### ISSUE TITLE
Icon size for all page elements

### ISSUE THREAD

**Issue by exebeeche** [status-im/help.status.im#154]

**Comment by exebeeche** [comment]
I have tested several sizes of icons and there is no any difference between a size. Any inline icon will fit to a line size. Here in the example there are two icons, the profile on is 20x20, the avatar is 48x48. And they are equal sizes.

![Image](https://user-images.githubusercontent.com/44062246/177970858-bfd3ec90-3723-4a3e-8b7d-718f605d9be9.png)

**Comment by exebeeche** [comment]
Also any size of an icon does not affect on the space between lines in blocks or list bullets.

**Comment by jorge-campo** [comment]
Superseded by https://github.com/status-im/help.status.im/issues/230.
