### ISSUE TITLE
Update mkdocs.yml in Status writing style guide to Material insiders build

### ISSUE THREAD

**Issue by jorge-campo** [status-im/help.status.im#157]
The `mkdocs.yml` configuration file for the writing style guide should keep in synch with the one under the `config/en` directory.

**Comment by exebeeche** [comment]
Apparently, there is already the Insiders label on the footer of our Style guide. So here is the differences info:

`en/mkdocs.yml`

- 31 line, color option: `primary: white`
- 94 line, html plugin: `md_in_html`
- 96 line, headers level: `toc_depth: 2`
- 127 line, inherit line: `INHERIT: '../../overrides/mkdocs.insiders.yml'`

`style-guide/mkdocs.yml`

- 31 line, color option: `primary: deep purple`
- 83 line, snipets plugin: `pymdownx.snippets`

Each config file contains color option with different values. Other lines are unique for the relevant config files.

**Comment by jorge-campo** [comment]
Thanks, @exebeeche ,

I double-checked the Jenkins script and yes, the Style Guide is now built using Insiders.

Regarding the changes to do, could you please take care of these?

- [ ] in `style-guide/mkdocs.yml`:
- Adding the `md_in_html` option and `INHERIT: '../../overrides/mkdocs.insiders.yml` directive.
- [ ] in `en/mkdocs.yml`
- No changes; the `pymdownx.snippets` option exists in en/mkdocs.yml.

Thanks.

**Comment by exebeeche** [comment]
No problem, I will fix the `style-guide/mkdocs.yml` file.
