### ISSUE TITLE
Enable the "Anchor tracking" setting in the Style guide mkdocs.yml config. file

### ISSUE THREAD

**Issue by jorge-campo** [status-im/help.status.im#158]
See the [Anchor tracking ](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-tracking) setting in the Material for MkDocs configuration site.

This configuration only applies to the style guide; it does not apply to Status Help.

**Comment by exebeeche** [comment]
Anchors settings are on the dev-site:
https://dev-help.status.im/style-guide/structuring-the-content/#guidelines

**Comment by jorge-campo** [comment]
Hey @exebeeche, I'm sure I saw those anchors working last week on the dev- site, but they seem to be gone now (?)

**Comment by jorge-campo** [comment]
This is not the first time this has happened. Please, submit some changes to the developer branch (any change, doesn't matter) and check that Jenkins is picking up the task at [https://ci.status.im/job/website/job/dev-help.status.im/](https://ci.status.im/job/website/job/dev-help.status.im/).

If the changes are not reflected as you expect please, open an issue on our repo with the `CI` tag, explain what's going on, and assign the ticket to Jakub. It's also good that you contact him on the `#infra` channel about this.
