### ISSUE TITLE
Document required Material for MkDocs pip packages in README.md

### ISSUE THREAD

**Issue by jorge-campo** [status-im/help.status.im#164]
Include the list of pip packages we need to build the site using Material for MkDocs. Because we're using some extensions, they need specific packages to work.

**Comment by jorge-campo** [comment]
Completed in 491a3ca032e9a586ffb95aad3a6caee25d210c32.

**Comment by jakubgs** [comment]
* https://github.com/status-im/help.status.im/pull/188
