### ISSUE TITLE
Jenkins error building dev- and prod Status Help websites

### ISSUE THREAD

**Issue by jorge-campo** [status-im/help.status.im#195]
This is a follow-up to https://github.com/status-im/help.status.im/pull/189.

**Problem:**
The [dev-help.status.im](dev-help.status.im) (development) and [help.status.im](help.status.im) sites (production) don't build after merging or rebasing.

**Result:**
- We merge content into the `develop` branch, but Jenkins doesn't pick up the changes. Nothing occurs in https://ci.status.im/job/website/job/dev-help.status.im/
- We rebase `master` on `develop`, and Jenkins picks up the changes but fails with the following error:

```
15:34:11  + ghp-import -p generated
15:34:11  /home/jenkins/workspace/website/help.status.im@tmp/durable-da65cbc2/script.sh: line 1: ghp-import: not found
```

**Expected result:**
- [dev-help.status.im](dev-help.status.im) (development) and [help.status.im](help.status.im) (production) sites build with no issues.

Note: this problem has existed since we moved to Docker builds (see https://github.com/status-im/help.status.im/pull/189)

**Comment by jakubgs** [comment]
`develop` doesn't build because I switched it to my PR branch:

https://cdn.discordapp.com/attachments/626045898878877696/1000053311602442423/unknown.png

**Comment by jakubgs** [comment]
As for `master` that is indeed an issue, since we now build in a Docker container, and that doesn't contain the `ghp-import` tool:
https://github.com/status-im/help.status.im/blob/98967a890f5922c5db0d4217e9ad85a351db2fb2/Dockerfile#L10-L14

**Comment by jorge-campo** [comment]
Hey @jakubgs, I merged your update to the Dockerfile into `develop`, but the [dev-help.status.im](dev-help.status.im) build fails. Please, see https://ci.status.im/job/website/job/dev-help.status.im/88/.

**Comment by jakubgs** [comment]
Oooh, I see, the package for Alpine exists: https://pkgs.alpinelinux.org/packages?name=py3-ghp-import&branch=edge

![image](https://user-images.githubusercontent.com/2212681/181497873-37a4f2df-3f86-4781-97bc-7a385d94681c.png)

But it's just in `testing` repository. So it might make more sense to install it from Pip. Ugh.

**Comment by jakubgs** [comment]
Fixed: https://github.com/status-im/help.status.im/commit/d0346a91
Builds:

* https://ci.status.im/job/website/job/help.status.im/29/
* https://ci.status.im/job/website/job/dev-help.status.im/103/
