### ISSUE TITLE
Jenkins doesn't run after merging changes into the develop branch

### ISSUE THREAD

**Issue by jorge-campo** [status-im/help.status.im#243]
**Problem description:**
This problem affects our help.status.im repository.

After merging our topic branch into `develop`, Jenkins doesn't run and the dev-help.status.im website is not updated.

**Current result:**
Jenkins instance at [https://ci.infra.status.im/](https://ci.infra.status.im/) doesn't run and the [dev-help.status.im](dev-help.status.im) website is not updated with the latest changes from develop.

**Expected result:**
Jenkins instance at [https://ci.infra.status.im/](https://ci.infra.status.im/) runs and the [dev-help.status.im](dev-help.status.im) website is updated with the latest changes from develop.

**Comment by jakubgs** [comment]
Fixed.

**Comment by jakubgs** [comment]
Actually, the webhook URL was fixed, but there's another issue with Docker startup:
```
Step 4/5 : RUN addgroup -g 1001 jenkins  && adduser -D -u 1001 -G jenkins jenkins
 ---> Running in cc949c4bd626
failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: can't get final child's PID from pipe: EOF: unknown
```
https://ci.infra.status.im/job/website/job/dev-help.status.im/131/console

**Comment by jakubgs** [comment]
And thanks to my notes I can see that this is caused by duplicate entries in `/etc/subuid` and `/etc/subgid`:
```
admin@linux-01.he-eu-hel1.ci.release:~ % grep jenkins /etc/subgid
jenkins:0:65536
jenkins:0:65536

admin@linux-01.he-eu-hel1.ci.release:~ % grep jenkins /etc/subuid
jenkins:0:65536
jenkins:0:65536
```

**Comment by jakubgs** [comment]
Fixed:

* https://ci.infra.status.im/job/website/job/help.status.im/37/
* https://ci.infra.status.im/job/website/job/dev-help.status.im/132/
