### ISSUE TITLE
Sync your profile across devices

### ISSUE THREAD

**Issue by Fabiomorais87** [status-im/help.status.im#345]
For the best experience using Status on multiple devices, users should not recreate their Status account using their recovery phrase but synch new devices with existing ones.

**Comment by jorge-campo** [comment]
Check notes from https://github.com/status-im/help.status.im/issues/107 -- Some are still relevant for this topic.

**Comment by jorge-campo** [comment]
Hey @cheny0 , I had this on my backlog, but since you're in charge of "synching" and this is about how to sync a new device, I'm assigning this to you.
