### ISSUE TITLE
Remove CI jobs in help.status.im repo and unpublish https://docs.status.im website

### ISSUE THREAD

**Issue by jorge-campo** [status-im/help.status.im#701]
**Description**

Hello – I need your assistance in removing the Jenkins/CI jobs associated to this repo `status-im/help.status.im` and unpublishing the help.status.im website.

We have migrated our documentation to a new repository at `status-im\status-website` and a new website at https://status.app/help. We want to avoid confusion for the users who might access the old website/repo. Once this request is completed, we'll lock down the `status-im/help.status.im` repository and archive it in a few months.

**Current behavior**

`merge` request in the `status-im/help.status.im` repository trigger Jenkins CI jobs and update the https://help.status.im website.

**Expected behavior**

The CI jobs are no longer active in the `status-im/help.status.im` repository, and the https://help.status.im is unpublished.

>**Note:** We intentionally don't want a redirection https://help.status.im -> https://status.app/help

**Comment by jakubgs** [comment]
By `the https://help.status.im/ is unpublished` you mean you want to just take the website down?

**Comment by jakubgs** [comment]
I have for now disabled the CI jobs for this repo:

* https://ci.infra.status.im/job/website/job/help.status.im/
* https://ci.infra.status.im/job/website/job/dev-help.status.im/

I will remove them later. Just a precaution. And here's the removal of the page resources and DNS entries:

- [`infra-misc#6af80bef`](https://github.com/status-im/infra-misc/commit/6af80bef) - drop help.status.im and dev-help.status.im

I consider this done.
