### ISSUE TITLE
Change status-im/help.status.im repo visibility to "private"

### ISSUE THREAD

**Issue by jorge-campo** [status-im/help.status.im#702]
**Description**

Please change this repository's visibility to "private".

**Reason**

As part of the new Status website, the Status user documentation is no longer maintained in this repository, but in `status-im/status-website`. To avoid users and contributors confusion, we want to make this repository private.

**Current behavior**

The status-im/help.status.im GitHub repository is public and available to everyone.

**Expected behavior**

The status-im/help.status.im GitHub repository is private and available only to the Status Docs team, https://github.com/orgs/status-im/teams/docs. 

**Note**: we don't want to change the Docs GitHub project availability (https://github.com/orgs/status-im/projects/71)

**Comment by jakubgs** [comment]
Why are you writing all of this when you can do this yourself?

![image](https://github.com/status-im/help.status.im/assets/2212681/37ec61c5-09f9-45e3-8102-182808f557ca)

**Comment by jorge-campo** [comment]
> Why are you writing all of this when you can do this yourself?
> 
> ![image](https://user-images.githubusercontent.com/2212681/278003007-37ec61c5-09f9-45e3-8102-182808f557ca.png)

Because I tried to do it by myself, but I don't have the rights 😄 

![Screenshot 2023-10-25 at 2  58 21@2x](https://github.com/status-im/help.status.im/assets/62282406/8dc2a3cc-bfc2-43b0-b01a-237fd64b3535)

Could you please make the repo private, @jakubgs ? Thanks.

**Comment by jakubgs** [comment]
Oh, it's because of private repo limit, normally you'd have the permissions:

![image](https://github.com/status-im/help.status.im/assets/2212681/284cae74-b72f-48e7-8a94-4ed3be93d7a8)

I don't know if we have any private repos we can remove.

Why exactly does this need to be private? Seems kinda silly to me.

**Comment by jakubgs** [comment]
If you want to "avoid confusion" we can just add a deprecation banner at the top of the `README` and archive this repo.

Making it private seems weird to me, nothing here is actually sensitive.

**Comment by jorge-campo** [comment]
No worries, then. I'll update the repo's README.md and archive it for good. Thanks.
