### ISSUE TITLE
First steps using the Status app

### ISSUE THREAD

**Issue by jorge-campo** [status-im/help.status.im#97]
This article explains the recommended first steps for a new Status user:

1. Fill out the user profile
2. Configure notifications
3. Learn how to send messages
4. Learn other app functionalities (or Join a Status Community)
5. Backup the seed phrase

> **Note**
> This article goes along https://github.com/status-im/help.status.im/issues/41

**Comment by jorge-campo** [comment]
The goal of this article is now a quick start guide, where we introduce users to the different Status sections (messaging, communities, wallet, Web3 browser).

We can also give users some tips to start using Status, like the ones mentioned in the previous comment.

**Comment by mayowaolatunji** [comment]
# Quick Start Guide

**Prerequisite:**
Download status on [status.im/get](https://status.im/get/) & install for setup.

## Fill out the user profile
     Below are the few steps required to set up your user profile on status:

1. Open your Status App
2. Click on the  “I’m new, generate keys” to Access your account keys.
3. Choose a Chart name to continue the process.
4. Fill in your account password to complete the setup.

***
### Access or Modify your Profile:
Click on the settings Icon or profile image icon at the bottom left corner to locate your profile details.

-User name
-Profile Image
-Chat key
-profile URL/Barcode

**Comment by cheny0** [comment]
Content is already covered by status-im/help.status.im#41 status-im/status-website#150

**Comment by mayowaolatunji** [comment]
> Content is already covered by status-im/help.status.im#41 status-im/status-website#150

Hello @cheny0, What content would you like me to contribute to?
